### ISSUE TITLE
Issues when comparing byte[] to byte[] in queries

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/efcore#14240]
This is probably related with #13260 

byte[] is a reference type and 2 arrays of bytes aren't equal when they refer to different arrays. This is all fine, but it becomes a problem when using byte[] as a primary key. 

MySQL (among others) do not have a data type to store GUIDs, so we store them as byte(16). EFCore translates this to byte[]... 

The MySQL provider does compare byte[] correctly with another byte array (probably because they have internally made it a different type). The InMemory database does not, which is what we use for unit testing. 

The "SequenceEqual" method does work on the InMemory implementation, but I'm not sure if this is a correct workaround. 

In the past, Linq to SQL we had System.Data.Linq.Binary for this. This class implemented a implicit comparison to byte[].

### Further technical details
EF Core version: 8.0.13
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows
IDE: Visual Studio 2017 15.9.4

**Comment by ajcvickers** [comment]
@jeroenlandheer We fixed several issues with `byte[]` properties and the in-memory database for the 2.2 release. You say you are using version "8.0.13" but that's not an EF Core version. What version of the NuGet package do you have installed in your project? If it's not 2.2, then can you update to that and check whether or not the issues you are seeing are fixed?

**Comment by jeroenlandheer** [comment]
@ajcvickers Thank you for your response. Don't know where that weird version number came from, but the package is EFCore v2.2. I've upgraded the app (and test project to v2.2 as well, but the issue is still there. 

If I try .SequenceEquals(byte[]) I have no issues, when I use "==" it doesn't work. 

I store the GUID in a table as a byte[] array, next the repository class compares that with a Guid from a different instance that it converts to bytes using ".ToByteArray()" The array's contents are the same but the references to the arrays are different. 

        public async Task<SomeObject> GetAsync(Guid someId)
        {
            using (var entities = new SomeContext(configuration))
            {
                var item = await entities.SomeTable.SingleOrDefaultAsync(x => x.SomeObjectId == someId.ToByteArray());
                ...
		// item == null with the InMemoryDatabase and is not null with MySql database
            }
        }

If I do this then it works for both the InMemoryDatabase and the MySql database:

        public async Task<SomeObject> GetAsync(Guid someId)
        {
            using (var entities = new SomeContext(configuration))
            {
                var item = await entities.SomeTable.SingleOrDefaultAsync(x => x.SomeObjectId.SequenceEquals(someId.ToByteArray()));
                ...
		// item contains a record of SomeTable
            }
        }

Maybe this helps?

**Comment by ajcvickers** [comment]
@jeroenlandheer I'm having trouble following exactly what you are doing. In EF Core 2.2, assuming the provider is working correctly, a GUID property should be automatically converted to a byte array if the provider does not natively support GUIDs. Does this not work, or did you not try it? If it doesn't work, then explicitly configuring a value converter should work--see https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions

If none of this helps, then probably the best way forward would be for you to create a simple runnable project/solution or complete code listing such that there is no ambiguity and we can dig into whatever is not working.

**Comment by jeroenlandheer** [comment]
@ajcvickers  I've created a repo with a unit test demonstrating the issue with the InMemory database. 
https://github.com/jeroenlandheer/efcore-22-inmemorydb

I'll give your suggestions a try, I wasn't aware that there was a conversion for GUIDs in place.

**Comment by ajcvickers** [comment]
@jeroenlandheer I think I understand now--I was confused by how this was related to Guids. I was able to reproduce binary keys not working correctly in the in-memory database.

However, what I have been trying to say is that the MySQL provider should be able to map GUIDs, possibly using the built-in conversion to `byte[]` if there is no native mapping available. If the MySQL provider is not doing this, then please report it as a bug to them.

**Comment by smitpatel** [comment]
@ajcvickers - Is this different from #13260?

**Comment by ajcvickers** [comment]
@smitpatel Looks like a duplicate.

**Comment by jjxtra** [comment]
2.2 still fails to compare byte arrays using equals or sequenceequal

**Comment by ajcvickers** [comment]
@jjxtra Indeed. This issue is a duplicate of an issue in the backlog that has not yet been fixed.
