### ISSUE TITLE
error CS7068: Reference to type 'ModelBuilder' claims it is defined in this assembly, but it is not defined in source or any added modules

### ISSUE THREAD

**Issue by aguacongas** [dotnet/efcore#2253]
I use class library which reference EntityFramework.SqlServer, it doesn't compile with this message in build log:  
`DNX 4.5.1 error CS7068: Reference to type 'ModelBuilder' claims it is defined in this assembly, but it is not defined in source or any added modules`  
And VS 2015 RC says in bubble:  
`CS0012 The type 'DbContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.`  
`The type or namespace name 'ModelBuilder' could not be found (are you missing a using directive or an assembly reference)`  
`MissingPackage Type Microsoft.Data.Entity.ModelBuilder exists in the package: EntityFramework.Core 7.0.0-beta4, Supported frameworks: DNX 4.5.1;DNXCore 5.0;.NETFramework 4.5`  

In my project.json:

```
    "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta4",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
        "ChatLe.Repository": ""
    },
```

I tried by adding `"EntityFramework.Core": "7.0.0-beta4"`` but it's worst

The full code is on [my Githuh repo](https://github.com/aguacongas/chatle/tree/dev/src/ChatLe.Repository.Identity)

**Comment by rowanmiller** [comment]
@mikary can you try and repro this. Only the reference to the provider is needed. Possibly a DNX issue.

**Comment by aguacongas** [comment]
Ok, I found where was the problem:  
I've a submodule to a fork of EntityFramework in my solution. But this fork wasn't up to date for beta4

**Comment by aguacongas** [comment]
I reopen this issue, because after cleaning and uptating all to beta4 I still have the issue.
I tried to add a new class library project and just add a dependency to `Microsoft.AspNet.Identity.EntityFramework`and I've same issues.  

     "dependencies": {
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4"
    },

There's also a weird stuf, If I rebuild all the solution I don't have any error, If I build the project only, I've errors. And I can't start the web project in all cases.  
If you want reproduce the code is on (GitHub)[https://github.com/aguacongas/chatle/blob/dev/src/ChatLe.Repository.Identity]

**Comment by mikary** [comment]
I took a look at the solution and I noticed a number of issues (primarily related to API surface changes in EF around the Beta4 release). Some of the error messages are a bit misleading, but these changes should at least get you started down the right path:
* ```DbSet.AddAsync``` has been removed, use ```DbSet.Add``` instead
* ```DbSet.Remove(TEntity[])``` should be replaced with ```DbSet.RemoveRange(TEntity[])```
* ```DbContextOptions``` is now ```DbContextOptionsBuilder```
* ```ModelBuilder.HasOne``` has been replaced with ```ModelBuilder.Reference```
* ```ModelBuilder.WithMany``` has been replaced with ```ModelBuilder.InverseCollection```
* ```AddEntityFramework(IConfiguration)``` has been removed, EF currently needs to be configured programatically

There are also some changes to Migrations API and it might be easiest to understand these by pulling out the existing migrations and scaffolding new ones (Do you have any other suggestions for these @bricelam ?)

I believe there may also be changes to the Identity API, but I'm not as familiar with those.

While debugging I pulled out the references in the chatle project.json to 'EntityFramework.Redis" and "Firefly". I don't know if those have been updated for Beta4, but it may help reduce the noise in the error messages to pull them out.

**Comment by aguacongas** [comment]
@mikary

**Comment by aguacongas** [comment]
@mikary I fixed all build issues, but VS still complains and I can't generate migration:

     C:\Users\Olivier\Source\Repos\chatle\src\ChatLe.Repository.Identity>dnx . ef migration add initial -c ChatLeIdentityDbCo
    ntextSql
    Using context 'ChatLeIdentityDbContextSql'.
    Microsoft.Data.Entity.Metadata.ModelItemNotFoundException: The entity type 'ChatLe.Models.NotificationConnection`1[[Syst
    em.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' requires a key to be defined.
       at Microsoft.Data.Entity.Metadata.EntityType.GetPrimaryKey() in C:\Users\Olivier\Source\Repos\chatle\EntityFramework\
    src\EntityFramework.Core\Metadata\EntityType.cs:line 261
       at Microsoft.Data.Entity.Metadata.EntityType.Microsoft.Data.Entity.Metadata.IEntityType.GetPrimaryKey() in C:\Users\O
    livier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Core\Metadata\EntityType.cs:line 990
      at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.<Add>d__16.MoveNext() in C:\Users\Olivier\S
    ource\Repos\chatle\EntityFramework\src\EntityFramework.Relational\Migrations\Infrastructure\ModelDiffer.cs:line 278
       at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
       at System.Linq.Enumerable.<ConcatIterator>d__1`1.MoveNext()
       at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.Sort(IEnumerable`1 operations) in C:\Users\
    Olivier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Relational\Migrations\Infrastructure\ModelDiffer.cs:line
     79
       at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.GetDifferences(IModel source, IModel target
    ) in C:\Users\Olivier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Relational\Migrations\Infrastructure\Model
    Differ.cs:line 60
       at Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.ScaffoldMigration(String migrationName, String rootN
    amespace) in C:\Users\Olivier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Commands\Migrations\MigrationScaff
    older.cs:line 80
       at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String roo
    tNamespace, String projectDir) in C:\Users\Olivier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Commands\Migr
    ationTool.cs:line 55
       at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass9_0.<AddMigration>b__1() in C:\Users\Olivier\Source\Repos\
    chatle\EntityFramework\src\EntityFramework.Commands\Program.cs:line 233
       at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke) in C:\Users\Olivie
    r\Source\Repos\chatle\EntityFramework\src\EntityFramework.Commands\Program.cs:line 342
       at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject) in C:\User
    s\Olivier\Source\Repos\chatle\EntityFramework\src\EntityFramework.Commands\Program.cs:line 229
       at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_1.<Main>b__6() in C:\Users\Olivier\Source\Repos\chatle\E
    ntityFramework\src\EntityFramework.Commands\Program.cs:line 97
       at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args) in C:\Users\Olivier\.
    dnx\packages\Microsoft.Framework.CommandLineUtils\1.0.0-beta4\shared\CommandLineApplication.cs:line 278
       at Microsoft.Data.Entity.Commands.Program.Main(String[] args) in C:\Users\Olivier\Source\Repos\chatle\EntityFramework
    \src\EntityFramework.Commands\Program.cs:line 198

**Comment by aguacongas** [comment]
And the website start but with error 500:

[I saved it there](https://github.com/aguacongas/chatle/blob/dev/500%20Internal%20Server%20Error.mht)

And the weird thing is; if I set a dependency to `EntitFramework.Redis`, VisualStudio launch `EntityFramework.Core` project. but not from the submodule, I deleted it.
The [dnx log](https://github.com/aguacongas/chatle/blob/dev/Solution%20launch%20dnx%20log.txt)

**Comment by mikary** [comment]
There are a number of known issues in the migrations model snapshot in beta4 that have been resolved since then. The beta5 release is coming up soon and it might be best to try updating to the latest bits from there. The latest build is available at https://www.myget.org/F/aspnetrelease/api/v2

**Comment by aguacongas** [comment]
thx @mikary , what is the runtime version I have to used with this released ?

**Comment by mikary** [comment]
If you are on the release feed, you'll probably want to be taking the most recent versions of all of your packages. You can configure this in your project.json with a wildcard like:
```json
    "dependencies": {
        "EntityFramework.Commands": "7.0.0-*"
    }
```

Once the next release is out you'll want to switch to that, but for the most part, these packages should be close to what will be in the next release.

**Comment by aguacongas** [comment]
@mikary I'll try asap but not yet, thx

**Comment by mikary** [comment]
We just released beta5, so you should be able to use the normal feed to try generating the migrations. It looks like we've resolved your original issue with the `ModelBuilder`, so I'm going to close this out, but if you find additional problems with migrations, please open specific issues so that we can address them.

**Comment by emfluenceindia** [comment]
I am having the same issue. I have added the following dependencies in my `project.json` file:
```
"dependencies": {
    "EntityFramework": "7.0.0-beta4",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.SqlServer": "7.0.0-beta8",
    "EntityFramework.Commands": "7.0.0-rc1-final"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },
```
I used `dnu install EntityFramework` and `dnu install EntityFramework.SqlServer` to install the packages. `"EntityFramework": "7.0.0-beta4",` was written under `dependencies` node automatically by the installer itself.

Issue / Question 1: To my surprise when I was pulling in the intellisence for `EntityFramework` the available version I am presenting with is only `6.1.3`!

Issue 2: When I am compiling my application using `dnu build` (I ran `dnu restore` command after adding `EntityFramework` assemblies (`.Core` and `.Commands`) manually under `dependencies` node I am getting a bunch of compilation errors:

```
The type 'DbContextOptionsBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
D:\Projects\aspnet\apiservice\Models\SampleData.cs(12,41): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
D:\Projects\aspnet\apiservice\Models\SampleData.cs(13,32): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
D:\Projects\aspnet\apiservice\Models\SampleData.cs(14,29): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'Books' and no extension method 'Books' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
D:\Projects\aspnet\apiservice\Models\SampleData.cs(15,42): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'Authors' and no extension method 'Authors' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
D:\Projects\aspnet\apiservice\Models\SampleData.cs(17,43): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'Authors' and no extension method 'Authors' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
D:\Projects\aspnet\apiservice\Models\SampleData.cs(19,45): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'Authors' and no extension method 'Authors' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
D:\Projects\aspnet\apiservice\Models\SampleData.cs(22,29): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'Books' and no extension method 'Books' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
D:\Projects\aspnet\apiservice\Models\SampleData.cs(61,29): DNXCore,Version=v5.0 error CS1061: 'object' does not contain a definition for 'SaveChanges' and no extension method 'SaveChanges' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
```
If I remove `.Core` and `.Commands` assembly references the project build fine.

Then I changed the version for `EntityFramework.Core` to `7.0.0.0` as mentioned in the error:
`The type 'DbContextOptionsBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.`
But `dnu restore` now gave me the following:
```
Unable to locate Dependency EntityFramework.Core >= 7.0.0
Writing lock file D:\Projects\aspnet\apiservice\project.lock.json
Restore complete, 6675ms elapsed

Errors in D:\Projects\aspnet\apiservice\project.json
    Unable to locate Dependency EntityFramework.Core >= 7.0.0
```
I am screwed up!

**Comment by ErikEJ** [comment]
Your dependencies are screwed up!

    dependencies": {
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final"
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final"
  },

**Comment by emfluenceindia** [comment]
Thanks Erik! I just updated my packages references as you suggested. It now looks like this:

```
"dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "System.Net.Http": "4.0.1-beta-23516",
    "Microsoft.Net.Http": "2.2.29",
    "EntityFramework": "7.0.0-beta4",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final"
  },

Now I am getting a new error:

`D:\Projects\aspnet\apiservice\Models\SampleData.cs(2,17): DNXCore,Version=v5.0 error CS0234: The type or namespace name 'Framework' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`
```
This is coming from `using Microsoft.Framework.DependencyInjection;`. Rest of the errors still persist like:

```
D:\Projects\aspnet\apiservice\Models\SampleData.cs(12,41): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
D:\Projects\aspnet\apiservice\Models\SampleData.cs(13,32): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
```

**Comment by ErikEJ** [comment]
Remove "EntityFramework" (as I hinted at)

**Comment by emfluenceindia** [comment]
Thanks again for your continuous help! I removed "EntityFramework" reference from dependencies. 
Now it looks like:

```
"dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "System.Net.Http": "4.0.1-beta-23516",
    "Microsoft.Net.Http": "2.2.29",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final"
  },
```
Also removed the namespace `using Microsoft.Framework.DependencyInjection` from `SampleData.cs` file. Now the compiler is complaining about the following:

```
D:\Projects\aspnet\apiservice\Models\SampleData.cs(11,41): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
D:\Projects\aspnet\apiservice\Models\SampleData.cs(12,32): DNXCore,Version=v5.0 error CS0308: The non-generic method 'IServiceProvider.GetService(Type)' cannot be used with type arguments
```
