### ISSUE TITLE
EF Core 8.0.3 produces incorrect idempotent migration script

### ISSUE THREAD

**Issue by pekspro** [dotnet/efcore#33337]
After I updated a library from this:

```XML
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
```

To this:

```XML
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.3">
```

I get incorrect SQL when I'm build migration script. I run this command:

```
dotnet ef migrations script --startup-project ..\MyStartUpProject.csproj --context MyDatabaseContext --output migrations.sql --verbose --idempotent
```

Then I get a large SQL script. Almost everything is correct. But this correct snippet:

```SQL
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20200401082009_AddsCustomerGroupTables'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20200401082009_AddsCustomerGroupTables', N'8.0.2');
END;
GO
```

Is changed to:

```SQL
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20200401082009_AddsCustomerGroupTables'
)
BEGIN


END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20200401082009_AddsCustomerGroupTables'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20200401082009_AddsCustomerGroupTables', N'8.0.3');
END;
GO
```

Somehow, a `BEGIN` followed directly by and `END` is not valid SQL I guess.

I have checked this migration, and migrations before that, and I do not se anything special.

Unfortunate, I haven’t been able to reproduce this in a new library and I cannot share the code in public. But I do not mind sharing the code with someone in the team if needed. In my build pipeline I produced 6 migrations script, and only one of these has this problem.

### Include provider and version information

EF Core version: 8.0.3 / 8.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 8.0

**Comment by kemmis** [comment]
I'm having this exact issue. +1 please fix.

**Comment by pekspro** [comment]
I might have found was it causing this. If I have this migration class:

```C#
public partial class AddsCustomerGroupTables : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
      migrationBuilder.Sql(@"

SELECT GetDate()
GO

");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
      
  }
}
```

Then the incorrect SQL is generated. My current guess the that the `GO` keyword triggers some bad behavior. I'm using the Sql method a lot in migrations in my projects, but this is the only place were I use `GO`. @kemmis, can you see if you do the same?

**Comment by kemmis** [comment]
Yep, It's the last GO that causes this. I just fixed it in my project by updating about a dozen sql scripts that were triggering this.

**Comment by kristofdaems** [comment]
The problem is not the GO statement, it are the empty lines after the GO statement.

This issue started by this commit: https://github.com/dotnet/efcore/commit/9b8b38fa3f2fdc5c14dcf92453928cd38eb3dbc3#diff-c80a80f96194920fd36fd4daaa22d80408aaa7f083128172c4c05331f0b92de0
File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs

Before that commit, empty lines were ignored so no new batch was created after the GO statement. Now after the GO statement a new batch is started but only contains empty lines which is the error.

Proposed solution: check wether the batch is empty before adding it to the builder (MigrationCommandListBuilder)
If this is a valid solution, I can have a look at it to solve it.

**Comment by JakeYallop** [comment]
Just mentioning the actual PR that caused the break: https://github.com/dotnet/efcore/pull/32788

Unfortunately, setting the app context switch (which present in the backport PR, removed in the .NET 9.0 PR) does not resolve this specific issue.

**Comment by lorenzoregazzoni** [comment]
The issue is still present in 8.0.8 version
