### ISSUE TITLE
Using SharedTypeEntity cannot access entity from MemberExpression

### ISSUE THREAD

**Issue by makingbloke** [dotnet/efcore#35818]
### Question

I'm attempting to write an extension to EF Core which let's me do a freetext search in a query but does all the database specific stuff (such as temming, languages terms etc.) behind the scenes.

In my test project I have a entity (TestTableDto) which is setup as a SharedTableEntity in the context:
```
        modelBuilder.SharedTypeEntity<TestTableDto>("TestTable");
        modelBuilder.SharedTypeEntity<TestTableDto>("TestTable_Stemming");
```
I have a custom method called FreeTextSearch which I call with a column expression and some text to find in a query:
```
       IQueryable<TestTableDto> x = context.Set<TestTableDto>("TestTable").Where(e => EF.Functions.FreeTextSearch(e.TextContent!, "text to find"));
```
An interceptor based on IQueryExpressionInterceptor calls an ExpressionVisitor class which catches the FreeTextSearch calls and will eventually map them to the relevant freetext search functions in the database.
```
    protected override Expression VisitMethodCall(MethodCallExpression? node)
    {
        MethodInfo method = node!.Method;

        if (method == FreeTextSearchMethod)
        {
            // FreeTextSearch takes 3 arguments: typeof(DbFunctions), typeof(object), typeof(string)]
            if (node.Arguments[1] is not MemberExpression memberExpression)
            {
                throw new ArgumentException("Argument is not a property expression.", method.GetParameters()[1].Name);
            }
```
My problem is I have memberExpression (which contains the e.TextContent) but how can I get an IEntityType from this? I cannot do a context.Model.FindEntityType because the entity is a SharedEntityType and I do not appear to have access to the tablename. (I need to get an IEntityType so I can access table annotations).

Hopefully, this makes sense and I've given enough detail (I have a test project but it's quite complicated with setting up interceptors and translators so I haven't included it as I thought it might muddy the waters somewhat).

Thanks

### Your code

```csharp

```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.3

### Database provider

Microsoft.EntityFrameworkCore.SqlServer / Sqlite

### Target framework

.NET 9.0

### Operating system

Windows 11

**Comment by roji** [comment]
> My problem is I have memberExpression (which contains the e.TextContent) but how can I get an IEntityType from this?

IQueryExpressionInterceptor is a very low-level interceptor for LINQ expression trees, which runs very early in the query pipeline and does not provide access to model information such table names; it is thus limited by design, and what you're trying to do can't accomplished using that interceptor.

To be able to help further, I'd need to know why it is exactly that you need an interceptor here; EF already has a built-in translation for EF.Functions.FreeText() ([docs](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/functions#string-functions)) - what exactly are you trying to achieve?

**Comment by makingbloke** [comment]
The project I'm working on supports either SQLite or SQLServer as it's database (I cannot just use EF.Functions.FreeText as it is SQL Server specific). Instead of having database specific code in my business logic I'm attempting to create a method (FreeTextSearch) which can be used in LINQ queries and will tailor the SQL to use the free text methods for the particular the database.

So, in my IQueryExpressionInterceptor I execute a different visitor class depending on the the database type:
```
    /// <inheritdoc/>
    public Expression QueryCompilationStarting(Expression queryExpression, QueryExpressionEventData eventData)
    {
        Expression expression;

        string databaseType = eventData.Context!.Database.GetDatabaseType();

        switch (databaseType)
        {
            case DatabaseType.Sqlite:
                expression = FreeTextSqliteExpressionVisitor.Visit(eventData.Context, queryExpression);
                break;

            case DatabaseType.SqlServer:
                FreeTextSqlServerExpressionVisitor sqlServerVisitor = new();
                expression = sqlServerVisitor.Visit(queryExpression)!;
                break;

            default:
                throw new InvalidOperationException("Unsupported database type");
        }

        return expression;
    }

```    
And in my SQL Server visitor class (FreeTextSqlServerExpressionVisitor) I build an expression using the DbFunctions.Contains / FreeText methods depending on whether or not the user wants stemming in their query and whether a language term is provided.
```

    private static readonly MethodInfo[] SqlServerFreeTextSearchMethods =
    [
        typeof(SqlServerDbFunctionsExtensions).GetMethod(nameof(SqlServerDbFunctionsExtensions.Contains), [typeof(DbFunctions), typeof(object), typeof(string)])!,

        typeof(SqlServerDbFunctionsExtensions).GetMethod(nameof(SqlServerDbFunctionsExtensions.FreeText), [typeof(DbFunctions), typeof(object), typeof(string)])!,

        typeof(SqlServerDbFunctionsExtensions).GetMethod(nameof(SqlServerDbFunctionsExtensions.Contains), [typeof(DbFunctions), typeof(object), typeof(string), typeof(int)])!,

        typeof(SqlServerDbFunctionsExtensions).GetMethod(nameof(SqlServerDbFunctionsExtensions.FreeText), [typeof(DbFunctions), typeof(object), typeof(string), typeof(int)])!
    ];

    /// <inheritdoc/>
    protected override Expression VisitMethodCall(MethodCallExpression? node)
    {
        MethodInfo method = node!.Method;

        if (method == FreeTextSearchMethod)
        {
            List<string> argumentNames = [.. method.GetParameters().Select(p => p.Name)];

            int methodIndex = 0;
            List<Expression> arguments = [node.Arguments[0], node.Arguments[1], node.Arguments[2]];

            for (int i = 3; i < node.Arguments.Count; i++)
            {
                switch (argumentNames[i])
                {
                    case "useStemming":
                        ConstantExpression constantExpression = (ConstantExpression)node.Arguments[i];

                        if ((bool)constantExpression.Value!)
                        {
                            methodIndex |= 1;
                        }

                        break;

                    case "languageTerm":
                        methodIndex |= 2;
                        arguments.Add(node.Arguments[i]);
                        break;
                }
            }

            return Expression.Call(null, SqlServerFreeTextSearchMethods[methodIndex], arguments);
        }

        return base.VisitMethodCall(node!);
    }

```
For SQL Server this works beautifully!

The problem occurs with SQLite. In SQLite if you want to use stemming you must specify it when creating the FTS virtual table. So you end up with two free text tables - one for stemming and one without. As a workaround for this I have made the freetext tables SharedTypeEntity's in the context.
```

    modelBuilder
        .SharedTypeEntity<TestTableDto>("TestTable");

    modelBuilder
        .SharedTypeEntity<TestTableDto>("TestTable_Stemming");

```
Then inside the SQLite visitor class (FreeTextSqliteExpressionVisitor) I can override the VisitExtensionMethod and if the node is an EntityQueryRootExpression I can replace the expression with one that has the stemming / non stemming table name. EF generates the SQL correctly and because the CLR type is shared the query runs fine and the results are returned.

Also, inside the SQLite visitor class, I can override VisitMethodCall and get the stemming flag (similar to how I do it for SQL server) but as the entity is a SharedClrType - I know the type of the entity but I do not have any way of knowing the table name so I cannot tell which table needs to be replaced! (see method below).
```

    /// <inheritdoc/>
    protected override Expression VisitMethodCall(MethodCallExpression? node)
    {
        Expression? expression = null;
        MethodInfo method = node!.Method;

        if (!this._replaceTables &&
            FreeTextDbFunctionsExtensions.FreeTextSearchMethods.Contains(method))
        {
            List<string> argumentNames = [.. method.GetParameters().Select(p => p.Name)];

            if (node.Arguments[1] is not MemberExpression memberExpression)
            {
                throw new ArgumentException("Argument is not a property expression.", argumentNames[1]);
            }

            for (int i = 3; i < node.Arguments.Count; i++)
            {
                if (argumentNames[i] == "useStemming")
                {
                    ConstantExpression constantExpression = (ConstantExpression)node.Arguments[i];

                    if ((bool)constantExpression.Value!)
                    {
                        // At this point I know the type of the entity is memberExpression.Expression!.Type
                        // but how do we find out the tablename (as it is a shared CLR type) or get the IEntityType?
                        this._entityTypes.Add(memberExpression.Expression!.Type);
                    }

                    break;
                }
            }

            expression = Expression.Call(SqliteMatchMethod, node.Arguments[0], node.Arguments[2], node.Arguments[1]);
        }

        return expression ?? base.VisitMethodCall(node!);
    }

```
Put it simply, I'm trying to replace the table name in a query with a different one.

Hope this clears things up a little

Cheers

**Comment by roji** [comment]
Am I understanding correctly that you basically your query interceptor to replace an EntityQueryRootExpression (which refers to TestTable) with another EntityQueryRootExpression (which refers to TestTable_Stemming)?

> I cannot do a context.Model.FindEntityType because the entity is a SharedEntityType and I do not appear to have access to the tablename. (I need to get an IEntityType so I can access table annotations).

I'm not sure I'm understanding correctly... But in your interceptor you can go over the entity types in the model, find the one you want (as an IEntityType), and then get its table name you want. A shared entity type is just a regular IEntityType - it simply happens to share a CLR type with another IEntityType.

/cc @AndriySvyryd as this seems to be mainly about querying the model for shared entity types etc.

**Comment by makingbloke** [comment]
> Am I understanding correctly that you basically your query interceptor to replace an EntityQueryRootExpression (which refers to TestTable) with another EntityQueryRootExpression (which refers to TestTable_Stemming)?

Yes, you are correct. In SQLite when searching freetext if I want to use stemming I have to use a different table to a non-stemming query.

> I'm not sure I'm understanding correctly... But in your interceptor you can go over the entity types in the model, find the one you want (as an IEntityType), and then get its table name you want. A shared entity type is just a regular IEntityType - it simply happens to share a CLR type with another IEntityType.

Inside VisitMethodCall I can get the type of an entity with memberExpression.Expression!.Type. However, if I call context.Model.FindEntityType(memberExpression.Expression!.Type) then it always returns null because the entity is shared. To be able to get the IEntityType for a shared entity I need to know the tablename (because there are several entities sharing the same CLR type) and this doesn't seem to be available in VisitMethodCall.

I cannot find the one I want as you suggest because in VisitMethodCall I can only get the type of the entity so I cannot identify which entity it belongs to as there is no table name. 

>                         // At this point I know the type of the entity is memberExpression.Expression!.Type
>                         // but how do we find out the tablename (as it is a shared CLR type) or get the IEntityType?
>

**Comment by AndriySvyryd** [comment]
If you have `EntityQueryRootExpression` then it contains the reference to the non-stemming entity type, so you just need to use the other entity type mapped to the same CLR type.

**Comment by roji** [comment]
@makingbloke I understand now. Entity types have a name in the EF model - that's the string argument you're passing above to SharedTypeEntity (so `TestTable` and `TestTable_Stemming`). You can use that name to look up the exact entity type you want instead of passing the CLR type.

**Comment by makingbloke** [comment]
@roji The problem is inside VisitMethodCall I have no way of getting the name so cannot lookup the Entity Type. As I said, if I wasn't using a shared entity I wouldn't have this problem. I think I'm going to use @AndriySvyryds idea and assume the other class is the one for stemming. The downside with this approach is a class can only be shared between 2 entities but I guess I can live with that.

**Comment by roji** [comment]
@makingbloke I'm not sure I understand... Isn't it a matter of getting the name of IEntityType that's already in the tree (`TestTable`) and just appending `_Stemming`? Otherwise, where would you "get the name from" if you weren't inside VisitMethodCall?

**Comment by makingbloke** [comment]
If I didn't use shared objects then I could just find the IEntityType in VisitMethodCall. Because I'm using shared objects I cannot as inside VisitMethodCall I have no way of knowing the table name (unless I pass it in - but I don't really want to do this as something like the Stemming Table Name should be fixed in the Context).

Anyway, after sleeping on the problem and I'm going to attack it in a slightly different way. I'm not going to use Shared Clr objects. This means inside VisitMethodCall I can get the IEntityType and the value of a custom annotation I will setup containing the stemming table name. Finally, I'll capture the SQL in another interceptor and replace "tablename" with "Stemmingtablename" (outside of string constants). This way I don't have to worry about any limitations of shared clr objects.

Thanks for all your help anyways, I know you guys are exceedingly busy and I really do appreciate it.

**Comment by roji** [comment]
I still don't understand **how** you're looking to look up the IEntityType for the entity type representing the stemming table. In general, you can either look up entity types in the model via the CLR type, or via their model name. With shared type entity types you can't use the CLR type, since there are multiple entity types mapped to the same CLR type; so what's left is the name. As I wrote above, I would expect you to get the model (not table!) name of the IEntityType you have in the original EntityQueryRootExpression (the one representing the non-stemming table), and then apply some convention to that (e.g. append `_Stemming`) to find your **other** entity type by name.

Otherwise I'm simply not sure what you're trying to do and how you want to look up your entity type - regardless of this being in an interceptor... In other words, imagine you're outside the interceptor and have everything you need - how would you then look up the other entity type?

But it seems like you're going in a different direction, so I'll go ahead and close this for now.
