### ISSUE TITLE
Where can we get the latest release?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5241]
Hi,
Some time ago I reported [two](https://github.com/aspnet/EntityFramework/issues/5140) [bugs](https://github.com/aspnet/EntityFramework/issues/5138) in EF7.  
One of the developers closed both bug reports as having been fixed.
But there is nothing available in [NuGet](https://www.nuget.org/packages/EntityFramework.Core) with these fixes; the last available version is 7.0.0-rc1-final, which was published on 18 Nov 2015.
We also tried cloning the repo here, and we simply cannot get the solution to build; there are too many mysterious dependencies.
(We did run 'build initialize' and it failed in the build step.)
What can we do to get this working?
Thanks

**Comment by ErikEJ** [comment]
You can get the lastest bits from Myget, there are a number of feeds of different quality available https://github.com/aspnet/Home/wiki/NuGet-feeds

**Comment by Aequoris** [comment]
The mysterious dependencies are most likely the replacement of DNX with coreclr for rc2. I recommend watching the weekly standups on Scott Hanselmans youtube channel to catch up on the RC2 news.

**Comment by ErikEJ** [comment]
I can build latest without any issues, btw @shaulbehr - what was the error you got?

**Comment by dteichman** [comment]
@ErikEJ 
I am working with @shaulbehr.
This is the error we received:

C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: The "GenerateProjectLockTargets" task failed unexpectedly.\r [C:\AgileWork\E
ntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.
csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: System.ArgumentNullException: Value cannot be null.\r [C:\AgileWork\EntityFr
amework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: Parameter name: path\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFra
meworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at System.IO.File.ReadAllText(String path)\r [C:\AgileWork\EntityFramewor
k\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at InlineCode.GenerateProjectLockTargets.Execute() in c:\Users\Owner\AppD
ata\Local\Temp\d1unar2n.0.cs:line 85\r [C:\AgileWork\EntityFramework\src\Micros
oft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITas
kExecutionHost.Execute()\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFr
ameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.Mov
eNext() [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microso
ft.EntityFrameworkCore.csproj]
fail: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
fail: Stack trace:
   at View4c4c2a59d20f4501826318686208ff31.<RenderViewLevel0>b__d5() in c:\Users\Owner\AppData\Local\Temp\f2f6aece829146448d96b8e3455faacf-1.cs:line 11311
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View4c4c2a59d20f4501826318686208ff31.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\f2f6aece829146448d96b8e3455faacf-1.cs:line 3617
   at View4c4c2a59d20f4501826318686208ff31.<RenderViewLevel0>b__66() in c:\Users\Owner\AppData\Local\Temp\f2f6aece829146448d96b8e3455faacf-1.cs:line 4042
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by ErikEJ** [comment]
And you are in a clean folder and clear your nuget cache? http://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line

**Comment by dteichman** [comment]
I did start in a clean folder. Now I wiped the folder, cleared the nuget cache, recloned the repository, checked out the release branch, ran build initialize from command line, and

info:   commandline: src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj /t:GenerateProjectLockTargets /v:m /nologo /p:Configuration=Debug
info:   workingdir: C:\AgileWork\EntityFramework
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: The "GenerateProjectLockTargets" task failed unexpectedly.\r [C:\AgileWork\E
ntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.
csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: System.ArgumentNullException: Value cannot be null.\r [C:\AgileWork\EntityFr
amework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: Parameter name: path\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFra
meworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at System.IO.File.ReadAllText(String path)\r [C:\AgileWork\EntityFramewor
k\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at InlineCode.GenerateProjectLockTargets.Execute() in c:\Users\Owner\AppD
ata\Local\Temp\bz54eclo.0.cs:line 85\r [C:\AgileWork\EntityFramework\src\Micros
oft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITas
kExecutionHost.Execute()\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFr
ameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.Mov
eNext() [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microso
ft.EntityFrameworkCore.csproj]
fail: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
fail: Stack trace:
   at View8b98382232194bcca540447e83bc0edd.<RenderViewLevel0>b__d5() in c:\Users\Owner\AppData\Local\Temp\fb62ce8440f94963a10b536247712296-1.cs:line 11311
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View8b98382232194bcca540447e83bc0edd.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\fb62ce8440f94963a10b536247712296-1.cs:line 3617
   at View8b98382232194bcca540447e83bc0edd.<RenderViewLevel0>b__66() in c:\Users\Owner\AppData\Local\Temp\fb62ce8440f94963a10b536247712296-1.cs:line 4042
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by rowanmiller** [comment]
@dteichman do you have MSBuild or VS installed?

**Comment by dteichman** [comment]
@rowanmiller yes to both. MSBuild 14.0.23107.0
and Microsoft Visual Studio Enterprise 2015 Version 14.0.23107.0 D14REL

**Comment by ErikEJ** [comment]
DI you have Nuget 3.4 installed?

**Comment by dteichman** [comment]
@ErikEJ Actually I do, but I upgraded recently and I wasn't sure if it was before or after my above tests.
I cleaned everything up again. Fresh folder, clear nuget cache etc. and tried again.

Now I got this 

info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration.fileextensions/1.0.0-rc3-20777/microsoft.extensions.configuration.fileextensions.1.0.0-rc3-20777.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/system.xml.xpath/index.json 602ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.configuration/index.json 263ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.runtime.numerics/4.0.1-rc2-24008/system.runtime.numerics.4.0.1-rc2-24008.nupkg 3332ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.configuration.fileextensions/index.json 267ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.text.encoding.extensions/4.0.11-rc2-24008/system.text.encoding.extensions.4.0.11-rc2-24008.nupkg 3270ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.xml.xpath.xdocument/index.json 3181ms
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.Configuration.FileExtensions' 471ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/runtime.win7-x64.runtime.native.system.data.sqlclient.sni/4.0.1-rc2-24027/runtime.win7-x64.runtime.native.system.data.sqlclient.sni.4.0.1-rc2-24027.nupkg 3543ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration/index.json 608ms
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/8.0.3/newtonsoft.json.8.0.3.nupkg 599ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.fileextensions/index.json 666ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.io/4.1.0-rc2-24008/system.io.4.1.0-rc2-24008.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.xml.xpath/4.0.1-rc2-24008/system.xml.xpath.4.0.1-rc2-24008.nupkg 1026ms
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.Configuration' 998ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration.fileextensions/1.0.0-rc3-20777/microsoft.extensions.configuration.fileextensions.1.0.0-rc3-20777.nupkg 814ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.physical/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.FileProviders.Physical'
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration.environmentvariables/1.0.0-rc3-20777/microsoft.extensions.configuration.environmentvariables.1.0.0-rc3-20777.nupkg 1429ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.security.cryptography.algorithms/4.1.0-rc2-24008/system.security.cryptography.algorithms.4.1.0-rc2-24008.nupkg 4287ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/index.json 202ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/1.0.0-rc3-20777/microsoft.extensions.fileproviders.physical.1.0.0-rc3-20777.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/index.json 266ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.configuration/1.0.0-rc3-20777/microsoft.extensions.configuration.1.0.0-rc3-20777.nupkg 1155ms
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.FileProviders.Physical' 457ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.runtime.handles/4.0.1-rc2-24008/system.runtime.handles.4.0.1-rc2-24008.nupkg 4690ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.threading.tasks/4.0.11-rc2-24008/system.threading.tasks.4.0.11-rc2-24008.nupkg 4568ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.physical/index.json 623ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.io/4.1.0-rc2-24008/system.io.4.1.0-rc2-24008.nupkg 1319ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.fileproviders.physical/1.0.0-rc3-20777/microsoft.extensions.fileproviders.physical.1.0.0-rc3-20777.nupkg 1043ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.filesystemglobbing/1.0.0-rc3-20777/microsoft.extensions.filesystemglobbing.1.0.0-rc3-20777.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.security.cryptography.encoding/4.0.0-rc2-24008/system.security.cryptography.encoding.4.0.0-rc2-24008.nupkg 5534ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.testing.abstractions/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.Testing.Abstractions'
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.reporters/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/xunit.runner.reporters/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/xunit.runner.reporters/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='xunit.runner.reporters'
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.filesystemglobbing/1.0.0-rc3-20777/microsoft.extensions.filesystemglobbing.1.0.0-rc3-20777.nupkg 1254ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/index.json 255ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/index.json 266ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg 263ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/1.0.0-rc2-002426/microsoft.extensions.testing.abstractions.1.0.0-rc2-002426.nupkg
log  : Failed to download package from 'https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg'.
log  : Response status code does not indicate success: 404 (The specified blob does not exist.).
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/xunit.runner.reporters/index.json 262ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.reporters/index.json 346ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.reporters/2.1.0/xunit.runner.reporters.2.1.0.nupkg
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.Extensions.Testing.Abstractions' 459ms
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='xunit.runner.reporters' 455ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg 272ms
log  : Failed to download package from 'https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg'.
log  : Response status code does not indicate success: 404 (The specified blob does not exist.).
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.security.cryptography.primitives/4.0.0-rc2-24008/system.security.cryptography.primitives.4.0.0-rc2-24008.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/xunit.runner.reporters/index.json 622ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.testing.abstractions/index.json 669ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg 263ms
error: Failed to download package from 'https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.commandlineutils/1.0.0-rc2-20752/microsoft.extensions.commandlineutils.1.0.0-rc2-20752.nupkg'.
error: Response status code does not indicate success: 404 (The specified blob does not exist.).
error: Unable to load package 'Microsoft.Extensions.CommandLineUtils'.
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.reporters/2.1.0/xunit.runner.reporters.2.1.0.nupkg 1092ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.utility/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/xunit.runner.utility/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/xunit.runner.utility/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='xunit.runner.utility'
info :   GET https://api.nuget.org/v3-flatcontainer/system.net.http/4.0.0/system.net.http.4.0.0.nupkg
info :   GET https://api.nuget.org/v3-flatcontainer/system.net.primitives/4.0.0/system.net.primitives.4.0.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/system.net.primitives/4.0.0/system.net.primitives.4.0.0.nupkg 160ms
info :   OK https://api.nuget.org/v3-flatcontainer/system.net.http/4.0.0/system.net.http.4.0.0.nupkg 169ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.testing.abstractions/1.0.0-rc2-002426/microsoft.extensions.testing.abstractions.1.0.0-rc2-002426.nupkg 1458ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.resources.resourcemanager/4.0.1-rc2-24018/system.resources.resourcemanager.4.0.1-rc2-24018.nupkg
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.reflection.typeextensions/4.1.0-rc2-24018/system.reflection.typeextensions.4.1.0-rc2-24018.nupkg
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.dotnet.projectmodel/1.0.0-rc2-002426/microsoft.dotnet.projectmodel.1.0.0-rc2-002426.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.utility/index.json 292ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.diasymreader/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.utility/2.1.0/xunit.runner.utility.2.1.0.nupkg
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/xunit.runner.utility/index.json 304ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.diasymreader/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.DiaSymReader'
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.diasymreader.native/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader.native/index.json
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.diasymreader.native/index.json
info :   GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.DiaSymReader.Native'
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='xunit.runner.utility' 452ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.diasymreader/index.json 265ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.diasymreader.native/index.json 263ms
info :   OK https://api.nuget.org/v3-flatcontainer/xunit.runner.utility/index.json 592ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.diasymreader.native/index.json 268ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.diasymreader/index.json 301ms
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/runtime.native.system.security.cryptography/4.0.0-rc2-24008/runtime.native.system.security.cryptography.4.0.0-rc2-24008.nupkg
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.DiaSymReader' 532ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader.native/index.json 618ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader.native/1.3.3/microsoft.diasymreader.native.1.3.3.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader/index.json 685ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader/1.0.6/microsoft.diasymreader.1.0.6.nupkg
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg 783ms
log  : Failed to download package from 'https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg'.
log  : Response status code does not indicate success: 404 (The specified blob does not exist.).
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.dotnet.projectmodel/1.0.0-rc2-002426/microsoft.dotnet.projectmodel.1.0.0-rc2-002426.nupkg 883ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.security.cryptography.primitives/4.0.0-rc2-24008/system.security.cryptography.primitives.4.0.0-rc2-24008.nupkg 2078ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/xunit.runner.utility/2.1.0/xunit.runner.utility.2.1.0.nupkg 1004ms
info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg 268ms
log  : Failed to download package from 'https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg'.
log  : Response status code does not indicate success: 404 (The specified blob does not exist.).
info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/1.0.0-rc2-20752/microsoft.extensions.logging.abstractions.1.0.0-rc2-20752.nupkg
info :   OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.DiaSymReader.Native' 1124ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader.native/1.3.3/microsoft.diasymreader.native.1.3.3.nupkg 607ms
info :   OK https://myget-2e16.kxcdn.com/artifacts/aspnetcirelease/nuget/v3/flatcontainer/system.resources.resourcemanager/4.0.1-rc2-24018/system.resources.resourcemanager.4.0.1-rc2-24018.nupkg 1335ms
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.diasymreader/1.0.6/microsoft.diasymreader.1.0.6.nupkg 603ms
fail: Exit code 1 from dotnet
fail: Stack trace:
   at View60a9b250bef040da9ca9ebb6e7a8f1c9.<RenderViewLevel0>b__a4() in c:\Users\Owner\AppData\Local\Temp\65b21c22b45d4c48aeccca5dedefbd32-1.cs:line 9336
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View60a9b250bef040da9ca9ebb6e7a8f1c9.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\65b21c22b45d4c48aeccca5dedefbd32-1.cs:line 3615
   at View60a9b250bef040da9ca9ebb6e7a8f1c9.<RenderViewLevel0>b__66() in c:\Users\Owner\AppData\Local\Temp\65b21c22b45d4c48aeccca5dedefbd32-1.cs:line 4040
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by rowanmiller** [comment]
@dteichman are you trying to build the dev or release branch? That feed (aspnetcirelease) would only work with the release branch.

**Comment by dteichman** [comment]
@rowanmiller release

**Comment by rowanmiller** [comment]
The *ci* feeds have packages pushed pretty regularly and they aren't always a coherent set of packages... that feed is pretty volatile, but gives you the latest build of every component (which is why we use it for local dev work). The error you got makes me think you may have been restoring packages as our CI was part way thru uploading a new set. Errors like this are often resolved by cleaning you repo (`git clean -fdx`) and running `build.cmd` again. Can you give that a go.

**Comment by dteichman** [comment]
@rowanmiller thanks.
I tried git clean -fdx and then build.cmd, but still failed:

Installed:
    41 package(s) to src/Microsoft.EntityFrameworkCore.Tools/project.json
info: Run target: csproj-initialize
info: Exec
info:   program: C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
info:   commandline: src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj /t:GenerateProjectLockTargets /v:m /nologo /p:Configuration=Debug
info:   workingdir: C:\AgileWork\EntityFramework
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: The "GenerateProjectLockTargets" task failed unexpectedly
.\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: System.ArgumentNullException: Value cannot be null.\r [C:
\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: Parameter name: path\r [C:\AgileWork\EntityFramework\src\
Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at System.IO.File.ReadAllText(String path)\r [C:\Agile
Work\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at InlineCode.GenerateProjectLockTargets.Execute() in
c:\Users\Owner\AppData\Local\Temp\n1qike24.0.cs:line 85\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityF
rameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft
.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore
.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstant
iatedTask>d__26.MoveNext() [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
fail: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
fail: Stack trace:
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__cb() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 11249
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View9f879c61a90e4930a610b1e01bc8ec78.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 3591
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__65() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 4016
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View9f879c61a90e4930a610b1e01bc8ec78.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 3591
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__66() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 4033
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View9f879c61a90e4930a610b1e01bc8ec78.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 3591
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__67() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 4050
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View9f879c61a90e4930a610b1e01bc8ec78.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 3591
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__68() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 4067
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View9f879c61a90e4930a610b1e01bc8ec78.<RenderViewLevel0>b__60() in c:\Users\Owner\AppData\Local\Temp\2b9cc9281c2740f9a3f3e5ccbad74281-1.cs:line 3923
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)



THEN I tried starting with a clean directory again to test the theory and running build initialize (release branch):
I got:

Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://www.postsharp.net/nuget/packages
info: Run target: csproj-initialize
info: Exec
info:   program: C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
info:   commandline: src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj /t:GenerateProjectLockTargets /v:m /nologo /p:Configuration=Debug
info:   workingdir: C:\AgileWork\EntityFramework
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: The "GenerateProjectLockTargets" task failed unexpectedly
.\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: System.ArgumentNullException: Value cannot be null.\r [C:
\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018: Parameter name: path\r [C:\AgileWork\EntityFramework\src\
Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at System.IO.File.ReadAllText(String path)\r [C:\Agile
Work\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at InlineCode.GenerateProjectLockTargets.Execute() in
c:\Users\Owner\AppData\Local\Temp\w5muz4qi.0.cs:line 85\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityF
rameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft
.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore
.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstant
iatedTask>d__26.MoveNext() [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
fail: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
fail: Stack trace:
   at View8bbc537ac0434976abbad2db737ef36d.<RenderViewLevel0>b__cb() in c:\Users\Owner\AppData\Local\Temp\fb58b83687e340469751f35b69457d7d-1.cs:line 11252
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View8bbc537ac0434976abbad2db737ef36d.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\fb58b83687e340469751f35b69457d7d-1.cs:line 3591
   at View8bbc537ac0434976abbad2db737ef36d.<RenderViewLevel0>b__65() in c:\Users\Owner\AppData\Local\Temp\fb58b83687e340469751f35b69457d7d-1.cs:line 4019
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by rowanmiller** [comment]
Hey,

The output shows that you have the `aspnetcidev` feed in the mix, which would cause issues because it has RC3 packages on it. This is probably setup in your machine wide sources, can you remove it and try again (after cleaning your local repo).

```
Feeds used:
https://www.myget.org/F/aspnetcirelease/api/v3/index.json
https://api.nuget.org/v3/index.json
https://www.myget.org/F/aspnetcidev/api/v3/index.json
https://www.postsharp.net/nuget/packages
```

~Rowan

**Comment by dteichman** [comment]
@rowanmiller thanks. I removed the other mygets from my sources. deleted folder, recloned. checked out release. reset nuget. and ran build initialize, but still no success:

info : Committing restore...
log  : Writing lock file to disk. Path: C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore.Tools\project.lock.json
log  : src/Microsoft.EntityFrameworkCore.Tools/project.json
log  : Restore completed in 47068ms.

NuGet Config files used:
    C:\AgileWork\EntityFramework\NuGet.Config
    C:\Users\Owner\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\nuget-postsharp.config

Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.postsharp.net/nuget/packages

Installed:
    41 package(s) to src/Microsoft.EntityFrameworkCore.Tools/project.json
info: Run target: csproj-initialize
info: Exec
info:   program: C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
info:   commandline: src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj /t:GenerateProjectLockTargets /v:m /nologo /p:Configuration=Debug
info:   workingdir: C:\AgileWork\EntityFramework
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: The "GenerateProjectLockTargets" task failed unexpectedly.\r [C:\AgileWork\E
ntityFramework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.
csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: System.ArgumentNullException: Value cannot be null.\r [C:\AgileWork\EntityFr
amework\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8: Parameter name: path\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFra
meworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at System.IO.File.ReadAllText(String path)\r [C:\AgileWork\EntityFramewor
k\src\Microsoft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at InlineCode.GenerateProjectLockTargets.Execute() in c:\Users\Owner\AppD
ata\Local\Temp\bmk1lqnc.0.cs:line 85\r [C:\AgileWork\EntityFramework\src\Micros
oft.EntityFrameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITas
kExecutionHost.Execute()\r [C:\AgileWork\EntityFramework\src\Microsoft.EntityFr
ameworkCore\Microsoft.EntityFrameworkCore.csproj]
C:\AgileWork\EntityFramework\tools\EntityFramework.targets(116,5): error MSB401
8:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.Mov
eNext() [C:\AgileWork\EntityFramework\src\Microsoft.EntityFrameworkCore\Microso
ft.EntityFrameworkCore.csproj]
fail: Exit code 1 from C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
fail: Stack trace:
   at Viewd71191f2b49b4fe89edcf497d8e103ba.<RenderViewLevel0>b__cb() in c:\Users\Owner\AppData\Local\Temp\97cff94e888244e8ac76b555bea6131d-1.cs:line 11252
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewd71191f2b49b4fe89edcf497d8e103ba.StartingTarget(String name) in c:\Users\Owner\AppData\Local\Temp\97cff94e888244e8ac76b555bea6131d-1.cs:line 3591
   at Viewd71191f2b49b4fe89edcf497d8e103ba.<RenderViewLevel0>b__65() in c:\Users\Owner\AppData\Local\Temp\97cff94e888244e8ac76b555bea6131d-1.cs:line 4019
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by rowanmiller** [comment]
@dteichman as you've probably worked out by now, this is really a game of trial and error. Did you delete the contents of `%USERPROFILE%\.nuget`? With all the changes to package versions it's possible to get the NuGet cache in a bad state when using the nightly feeds.
