### ISSUE TITLE
EF doesn't map queries to SQL... at all :(

### ISSUE THREAD

**Issue by cbmek** [dotnet/efcore#6517]
### The issue

It seams that EF (`"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0"`) doesn't translate lambda expressions to SQL in my case, and does everything "in memory".
This code below is the same code I've been using in `7.0.0-rc1-final` and it used to utilize SQL queries:

``` C#
int c = _context.Participants.Count(); // count all
IQueryable<Participant> tmp = null;
string sr = "meme";
tmp = _context.Participants.Where(m => m.FirstName.Contains(sr) || m.LastName.Contains(sr));
tmp = tmp.OrderBy(m => m.LastName);
int fc = tmp.Count(); // count filtered

var resp = (await tmp.Skip(start).Take(length).ToListAsync()).Select(m => new ParticipantView()
{
  Id = m.Id,
  FirstName = m.FirstName,
  LastName = m.LastName
});
```

I expect it to do 3 queries:
1) count all
2) count filtered
3) select filtered and paged
...and it does execute 3 queries but they look like this:

1) `SELECT COUNT(*) FROM [Participants] AS [p]` // this one look ok
2) `SELECT [m].[Id], [m].[About], [m].[EmailAddress], [m].[FirstName], [m].[LastName], [m].[PhoneNumber] FROM [Participants] AS [m]` // this should do the count I guess, but if fetches all rows and cont in memory. It also should be filtered already.
3) `SELECT [m].[Id], [m].[About], [m].[EmailAddress], [m].[FirstName], [m].[LastName], [m].[PhoneNumber] FROM [Participants] AS [m] ORDER BY [m].[LastName]` // this should be filtered and paged. It again does filtering in memory.

Am I doing something wrong, or is there something wrong with `1.0.0` version?

**Comment by SimonOrdo** [comment]
I had some similar results with filtering and EF pulling too many records.  https://github.com/aspnet/EntityFramework/issues/6515

**Comment by rowanmiller** [comment]
Hey,

I'm not able to reproduce this. Here is the code I used to try and reproduce the issue using the 1.0.0 packages:

```c#
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace PerfIssue.RC2
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new TestContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                int c = context.Participants.Count(); // count all
                IQueryable<Participant> tmp = null;
                string sr = "meme";
                tmp = context.Participants.Where(m => m.FirstName.Contains(sr) || m.LastName.Contains(sr));
                tmp = tmp.OrderBy(m => m.LastName);
                int fc = tmp.Count(); // count filtered
                var start = 1;
                var length = 1;
                var resp = (tmp.Skip(start).Take(length).ToList()).Select(m => new ParticipantView()
                {
                    Id = m.Id,
                    FirstName = m.FirstName,
                    LastName = m.LastName
                });

            }
        }
    }

    public class TestContext : DbContext
    {
        public DbSet<Participant> Participants { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestDb;Trusted_Connection=True;");
        }
    }


    public class Participant
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    public class ParticipantView
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

And here are the three queries I see in SQL Profiler:

```sql
SELECT COUNT(*)
FROM [Participants] AS [p]
```

```sql
exec sp_executesql N'SELECT COUNT(*)
FROM [Participants] AS [m]
WHERE [m].[FirstName] LIKE (N''%'' + @__sr_0) + N''%'' OR [m].[LastName] LIKE (N''%'' + @__sr_1) + N''%''',N'@__sr_0 nvarchar(4000),@__sr_1 nvarchar(4000)',@__sr_0=N'meme',@__sr_1=N'meme'
```

```sql
exec sp_executesql N'SELECT [m].[Id], [m].[FirstName], [m].[LastName]
FROM [Participants] AS [m]
WHERE [m].[FirstName] LIKE (N''%'' + @__sr_0) + N''%'' OR [m].[LastName] LIKE (N''%'' + @__sr_1) + N''%''
ORDER BY [m].[LastName]
OFFSET @__p_2 ROWS FETCH NEXT @__p_3 ROWS ONLY',N'@__sr_0 nvarchar(4000),@__sr_1 nvarchar(4000),@__p_2 int,@__p_3 int',@__sr_0=N'meme',@__sr_1=N'meme',@__p_2=1,@__p_3=1
```

Can you adjust the code to demonstrate the issue you are seeing.

~Rowan

**Comment by cbmek** [comment]
Hi, I've just found out that it's not due to `.Contains()` in query but the other part I removed in my example... because I didn't expect it to break the query. Here is my full query and below the console log from debug. When I remove the last condition it generetes good SQL query with COUNT/WHERE and pageing.

It seams that string formatiing is not applied and EF doesn't know what to do with query.

```csharp
tmp = _context.Participants.Where(m => m.FirstName.ToLower().Contains(sr) || m.LastName.ToLower().Contains(sr) || $"#{m.Id}" == sr);
```

```
icrosoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '(([m].FirstName.ToLower().Contains(__sr_0) OrElse [m].LastName.ToLower().Contains(__sr_1)) OrElse (Format("#{0}", Convert([m].Id)) == __sr_2))' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Count()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m].[Id], [m].[About], [m].[EmailAddress], [m].[FirstName], [m].[LastName], [m].[PhoneNumber]
FROM [Participants] AS [m]
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression '(([m].FirstName.ToLower().Contains(__sr_0) OrElse [m].LastName.ToLower().Contains(__sr_1)) OrElse (Format("#{0}", Convert([m].Id)) == __sr_2))' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Skip(__p_3)' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: Warning: The LINQ expression 'Take(__p_4)' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
The thread 0x6368 has exited with code 0 (0x0).
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory: Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [m].[Id], [m].[About], [m].[EmailAddress], [m].[FirstName], [m].[LastName], [m].[PhoneNumber]
FROM [Participants] AS [m]
ORDER BY [m].[LastName]
```

**Comment by rowanmiller** [comment]
Correct, EF doesn't know how to translate string interpolation (or `string.Format`) to SQL. String interpolation may be pretty difficult to translate, but we opened https://github.com/aspnet/EntityFramework/issues/6532 to take a look at it.

You can rewrite it like this for the moment and it will eval in the database `"#" + m.Id == sr`

BTW for more info on client eval (including disabling it) see https://docs.efproject.net/en/latest/querying/client-eval.html.

**Comment by cbmek** [comment]
@rowanmiller I did disable "client eval" and I was a happy men untill I tried to add some roles to user (using `UserManager<ApplicationUser>`). 
In UserStore they use `SingleOrDefault()`, and it can't be translated to server side query according to this Exception:
```
InvalidOperationException: Warning as error exception for warning 'RelationalEventId.QueryClientEvaluationWarning': The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

In my opinion using `SingleOrDefault()` in case when query uses Id, which is unique in DB anyway, is like instaliing AirBags in your bed. Isn't it a case that `FiresOrDefault()` is like 10 times faster than `SingleOrDefault()` - did someone made a speed test?

I'm not sure if I should report it here or in the Identity repo.

In scaffolding for MVC Controller they also use `SingleOrDefault()` which probably affects performance:
```
            var @Model.ModelVariable = await _context.@(entitySetName)@inlineIncludes
                .SingleOrDefaultAsync(m => m.@primaryKeyName == id);
            if (@Model.ModelVariable == null)
            {
                return NotFound();
            }
```

**Comment by rowanmiller** [comment]
@cbmek that warning is a false positive, we already fixed the issue and it will ship in 1.1.0 https://github.com/aspnet/EntityFramework/issues/5897

**Comment by ajcvickers** [comment]
@divega Shouldn't Identity be using FirstOrDefault? Or Find in 1.1? Likewise for MVC templates/scaffolding?

**Comment by divega** [comment]
@ajcvickers we should consider changing Identity and template code to use `FirstOrDefaultAsync()` or `FindAsync()` when applicable for performance. Note that the fact that `SingleOrDefault()` causes client-side evaluation warning even when applied at the top of the query was a bug that should already been fixed in 1.1.

FWIW, we could consider being smarter about `First/Single[OrDefault]()` translation when the predicate is equality on a key or unique constrain, since we can assume there won't be duplicates.

**Comment by divega** [comment]
Filed https://github.com/aspnet/EntityFramework/issues/6595 for possibly optimizing this in EF. 

There is also https://github.com/aspnet/EntityFramework/issues/1948 about using `Find()` semantics implicitly for such queries. 

I created https://github.com/aspnet/Identity/issues/975 and https://github.com/aspnet/Scaffolding/issues/300.

**Comment by brager17** [comment]
@rowanmiller 
In version 3 is not fixed this problem?
Why you think that interpolation is difficult to convert, it's just a call to the string.Format method with reference types or value types.
