### ISSUE TITLE
Root cause pipes issue on SQLClient

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#9031]
This has been an issue for years:

> System.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - No process is on the other end of the pipe.)
---- System.ComponentModel.Win32Exception : No process is on the other end of the pipe

After 2.0 is locked down, let's sync with the SqlClient team to try to get to the root cause and see if it can be fixed.

**Comment by ajcvickers** [comment]
@divega Can you find your simple repro for this?

**Comment by smitpatel** [comment]
@divega @ajcvickers @glennc - Should we do something about Triage to Ready back & forth transitions?

**Comment by divega** [comment]
@glennc this actually doesn't look right. Is it a bug in some script? Otherwise, can you just remove EF repo from the projects?

**Comment by ajcvickers** [comment]
I think @glennc should definitely do something about this! 😺

**Comment by ryanbrandenburg** [comment]
This continues to be an issue as seen [here](http://aspnetci/viewLog.html?buildId=363361&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId8936373169025784767).

**Comment by ryanbrandenburg** [comment]
Still seeing [this](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=411530&_focus=132453) occasionally, though less frequently.

**Comment by ajcvickers** [comment]
Assigned to @smitpatel to add some mitigations to the database creation tests, which is where this commonly shows up. This code doesn't change much, so one option is to not run them on the normal C.I. runs. Another is to add try-catch as appropriate to stop the tests from failing when this issue pops up.

**Comment by smitpatel** [comment]
While searching for error online, I found some suggestions which said, it could happen if tcp connection has higher priority than np (named pipes). And putting np first could resolve the issue. I checked efci agent to see configuration (where this error does not happen) and found that it does not have tcp enabled. I looked at the history of the build config on aspnetci to see agents where it failed last. I updated on agent 107 (where it failed only once in last 2 month or so) and tried to update aforementioned settings. In theory it should fix it.

Closing this issue as resolved for now.
If it fails again on different agent then we can apply same settings to other agent. If it fails on agent after above settings then we can look into disabling/skipping tests.

**Comment by ryanbrandenburg** [comment]
This is still happening. A list of these failures can be found [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:LoginError,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).
